<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shirkadayda</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            color: #333;
        }
        header {
            background-color: #6c63ff;
            color: white;
            padding: 20px 0;
            text-align: center;
        }
        header h1 {
            margin: 0;
            font-size: 2.5em;
        }
        section {
            padding: 20px;
            margin: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        #bio {
            text-align: center;
        }
        #portfolio {
            display: flex;
            justify-content: space-around;
            flex-wrap: wrap;
        }
        .project {
            width: 30%;
            margin: 10px 0;
            padding: 15px;
            background-color: #eef;
            border-radius: 8px;
            text-align: center;
        }
        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 10px 0;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
        footer a {
            color: #6c63ff;
            text-decoration: none;
            margin: 0 10px;
        }
    </style>
</head>
<body>

    <header>
        <h1>Shirkadayda</h1>
        <p>Kusoo dhawoow boggayga shakhsiyeed!</p>
    </header>

    <section id="bio">
        <h2>Nagu Saabsan</h2>
        <p>Shirkaddayadu waa mid holwadeeda aad ugu xeel dheer oo ku takhasustay qabashada howlaha kala duwan ee aad u baahan tahay. Waxaan ku faanaynaa inaan bixino adeegyo tayo sare leh oo dhamaystiran, si aan u daboolno baahiyaha macaamiisheena dhammaan dhinacyada shaqooyinka kala duwan.</p>
    </section>

    <section id="portfolio">
        <h2>Mashaariicdayada</h2>
        <div class="project">
            <h3>Mashruuca 1</h3>
            <p>Sharaxaadda mashruuca 1.</p>
        </div>
        <div class="project">
            <h3>Mashruuca 2</h3>
            <p>Sharaxaadda mashruuca 2.</p>
        </div>
        <div class="project">
            <h3>Mashruuca 3</h3>
            <p>Sharaxaadda mashruuca 3.</p>
        </div>
    </section>

    <section id="contact">
        <h2>Nala Soo Xiriir</h2>
        <p>Waan kugu soo dhaweynaynaa inaad nala soo xiriirto ama aad nagala xidhiidho baraha bulshada!</p>
        <p>Email: <a href="mailto:youremail@example.com">youremail@example.com</a></p>
        <p>
            <a href="https://www.linkedin.com">LinkedIn</a> |
            <a href="https://www.twitter.com">Twitter</a> |
            <a href="https://www.github.com">GitHub</a>
        </p>
    </section>

    <footer>
        <p>&copy; 2024 Shirkadayda. Dhammaan xuquuqaha way dhowrsan yihiin.</p>
    </footer>

</body>
</html>
